version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL:-http://host.docker.internal:55321}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY:-sb_publishable_ACJWlzQHlZjBrEguHvfOxg_3BJgxAaH}
        NEXT_PUBLIC_PROMPTPAY_ID: ${NEXT_PUBLIC_PROMPTPAY_ID:-0992142626}
        NEXT_PUBLIC_PROMPTPAY_NAME: ${NEXT_PUBLIC_PROMPTPAY_NAME:-ณฐนนท บุญพรหม}
        NEXT_PUBLIC_PAYMENT_ID: ${NEXT_PUBLIC_PAYMENT_ID:-1553093445}
        NEXT_PUBLIC_PAYMENT_NAME: ${NEXT_PUBLIC_PAYMENT_NAME:-KBank}
        NEXT_PUBLIC_PAYMENT_ACCOUNT: ${NEXT_PUBLIC_PAYMENT_ACCOUNT:-ณฐนนท บุญพรหม}
    image: leagueflow:latest
    container_name: leagueflow-web
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3000:3000"
    env_file:
      - .env.local
