"use client";

import { useActionState } from "react";
import { useSearchParams } from "next/navigation";
import { updateTournament, resetFixtures, deleteTournament, confirmPayment } from "@/app/[locale]/dashboard/tournaments/[id]/actions";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Separator } from "@/components/ui/separator";
import { useTransition } from "react";
import { ActionResponse } from "@/types/index";
import { useTranslations } from "next-intl";
import { Badge } from "@/components/ui/badge";
import { useState, useEffect, useCallback, useRef } from "react";
import { useToast } from "@/hooks/use-toast";
import { Check, X, Loader2, RefreshCw, Clock } from "lucide-react";
import { Link } from "@/i18n/routing";
import { createPromptPayCharge, checkChargeStatus } from "@/app/[locale]/actions/payment";
import { CollaboratorsCard } from "@/components/tournaments/collaborators-card";

const initialState: ActionResponse = {
    success: false,
    error: undefined,
};

export function SettingsTab({ tournament, hasFixtures, userPlan }: { tournament: any; hasFixtures: boolean; userPlan?: string }) {
    const tournamentId = tournament.id;
    const t = useTranslations("Settings");
    const tBilling = useTranslations("Billing");
    const tCommon = useTranslations("Common");
    const tDialog = useTranslations("Dialog");
    const updateTournamentWithId = updateTournament.bind(null, tournament.id);
    const [state, formAction] = useActionState(updateTournamentWithId, initialState);
    const [isPending, startTransition] = useTransition();

    const isGlobalPro = userPlan === 'monthly' || userPlan === 'yearly';
    const isTournamentPro = tournament.plan && tournament.plan !== 'free';
    const isPro = isGlobalPro || isTournamentPro;

    const { toast } = useToast();

    // Payment State
    const [showPayment, setShowPayment] = useState(false);
    const [isGeneratingQR, setIsGeneratingQR] = useState(false);
    const [isCheckingStatus, setIsCheckingStatus] = useState(false);
    const [paymentState, setPaymentState] = useState<{
        qrCode: string | null;
        chargeId: string | null;
        status: 'pending' | 'success' | 'failed';
    }>({ qrCode: null, chargeId: null, status: 'pending' });

    // 24 hours in seconds (1 day)
    const [timeLeft, setTimeLeft] = useState(24 * 60 * 60);

    const searchParams = useSearchParams();
    const isGeneratingRef = useRef(false);
    const hasAutoGeneratedRef = useRef(false);

    useEffect(() => {
        if (searchParams.get("action") === "upgrade" && !isPro && !showPayment) {
            // Safe Auto-Gen with double-lock
            if (
                !showPayment &&
                !paymentState.qrCode &&
                !isGeneratingRef.current &&
                !hasAutoGeneratedRef.current
            ) {
                hasAutoGeneratedRef.current = true;
                handleGenerateQR();
            }
            setShowPayment(true);
        }
    }, [searchParams, isPro, showPayment]);

    useEffect(() => {
        if (!showPayment || !paymentState.qrCode || paymentState.status === 'success') return;

        if (timeLeft <= 0) return;

        const timer = setInterval(() => {
            setTimeLeft((prev) => prev - 1);
        }, 1000);

        return () => clearInterval(timer);
    }, [showPayment, paymentState.qrCode, paymentState.status, timeLeft]);

    const handleGenerateQR = async () => {
        if (isGeneratingRef.current) return;
        isGeneratingRef.current = true;
        setIsGeneratingQR(true);
        setTimeLeft(24 * 60 * 60); // Reset timer to 1 day
        try {
            const res = await createPromptPayCharge(59000, { tournament_id: tournament.id }); // 590.00 THB
            if (res.success && res.data) {
                setPaymentState({
                    qrCode: res.data.qr_image,
                    chargeId: res.data.charge_id,
                    status: 'pending'
                });
            } else {
                toast({ title: tCommon("error"), description: res.error || "Failed to generate QR", variant: "destructive" });
            }
        } catch (error) {
            toast({ title: tCommon("error"), description: "Something went wrong", variant: "destructive" });
        } finally {
            setIsGeneratingQR(false);
            isGeneratingRef.current = false;
        }
    };

    const togglePayment = () => {
        if (!showPayment && !paymentState.qrCode) {
            handleGenerateQR();
        }
        setShowPayment(!showPayment);
    };

    const formatTime = (seconds: number) => {
        const h = Math.floor(seconds / 3600);
        const m = Math.floor((seconds % 3600) / 60);
        const s = seconds % 60;
        if (h > 0) {
            return `${h}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}`;
        }
        return `${m}:${String(s).padStart(2, '0')}`;
    };

    const checkStatus = useCallback(async (silent = false) => {
        if (!paymentState.chargeId || paymentState.status === 'success') return;

        if (!silent) setIsCheckingStatus(true);
        try {
            const res = await checkChargeStatus(paymentState.chargeId);
            if (res.success && res.data) {
                if (res.data.status === 'successful') {
                    // Update Database
                    const confirmRes = await confirmPayment(
                        tournament.id,
                        paymentState.chargeId,
                        'promptpay'
                    );

                    if (confirmRes.success) {
                        setPaymentState(prev => ({ ...prev, status: 'success' }));
                        toast({ title: tBilling("payment_success"), description: tBilling("payment_success_desc") });

                        // Reload to reflect changes
                        setTimeout(() => {
                            window.location.reload();
                        }, 2000);
                    } else {
                        if (!silent) toast({ title: tCommon("error"), description: "Failed to update payment status", variant: "destructive" });
                    }
                } else {
                    if (!silent) toast({ title: tBilling("payment_pending"), description: tBilling("payment_pending_desc") });
                }
            }
        } finally {
            if (!silent) setIsCheckingStatus(false);
        }
    }, [paymentState.chargeId, paymentState.status, tournament.id, tBilling, tCommon]);

    // Polling Effect - Use Ref to prevent interval clearing on re-renders
    const checkStatusRef = useRef(checkStatus);
    useEffect(() => {
        checkStatusRef.current = checkStatus;
    }, [checkStatus]);

    useEffect(() => {
        if (!showPayment || !paymentState.chargeId || paymentState.status !== 'pending') return;

        const timer = setInterval(() => {
            if (checkStatusRef.current) checkStatusRef.current(true);
        }, 3000);

        return () => clearInterval(timer);
    }, [showPayment, paymentState.chargeId, paymentState.status]);

    const handleCheckStatus = () => checkStatus(false);

    const handleReset = () => {
        if (confirm(t("reset_desc") + "?")) {
            startTransition(async () => {
                await resetFixtures(tournament.id);
            });
        }
    };

    const handleDelete = () => {
        if (confirm(t("delete_desc") + "?")) {
            startTransition(async () => {
                await deleteTournament(tournament.id);
            });
        }
    };

    return (
        <div className="space-y-6">
            {/* Collaborators Card */}
            <CollaboratorsCard tournamentId={tournamentId} />

            <Card>
                <CardHeader>
                    <CardTitle>{t("general_info")}</CardTitle>
                    <CardDescription>{t("update_details")}</CardDescription>
                </CardHeader>
                <CardContent>
                    <form action={formAction} className="space-y-4">
                        <div className="grid w-full max-w-sm gap-1.5">
                            <Label htmlFor="name">{tDialog("name")}</Label>
                            <Input type="text" id="name" name="name" defaultValue={tournament.name} placeholder={tDialog("name")} />
                        </div>
                        <div className="grid w-full max-w-sm gap-1.5">
                            <Label htmlFor="status">{t("status")}</Label>
                            <Select name="status" defaultValue={tournament.status || "draft"}>
                                <SelectTrigger>
                                    <SelectValue placeholder={t("select_status")} />
                                </SelectTrigger>
                                <SelectContent>
                                    <SelectItem value="draft">{t("draft")}</SelectItem>
                                    <SelectItem value="active">{t("active")}</SelectItem>
                                    <SelectItem value="completed">{t("completed")}</SelectItem>
                                </SelectContent>
                            </Select>
                        </div>
                        <div className="grid w-full max-w-sm gap-1.5">
                            <Label htmlFor="format">{t("format")}</Label>
                            <Select name="format" defaultValue={tournament.format || "league"}>
                                <SelectTrigger>
                                    <SelectValue placeholder={t("select_format")} />
                                </SelectTrigger>
                                <SelectContent>
                                    <SelectItem value="league">League</SelectItem>
                                    <SelectItem value="league_ha">League (Home/Away)</SelectItem>
                                    <SelectItem value="knockout">Knockout</SelectItem>
                                    <SelectItem value="group_knockout" disabled={!isPro}>
                                        Group + Knockout {!isPro && "(Pro Only)"}
                                    </SelectItem>
                                </SelectContent>
                            </Select>
                        </div>
                        {state.error && <p className="text-sm text-red-500">{state.error}</p>}
                        <div className="flex justify-between items-center">
                            <Button type="submit">{t("save_changes")}</Button>
                            {!isPro && (
                                <Button variant="outline" type="button" asChild>
                                    <a href="/dashboard/billing">Manage Billing</a>
                                </Button>
                            )}
                        </div>
                    </form>
                </CardContent>

            </Card>

            {/* Billing & Subscription Card */}
            <Card>
                <CardHeader>
                    <div className="flex items-center gap-2">
                        <CardTitle>{t("billing_title")}</CardTitle>
                    </div>
                    <CardDescription>{t("billing_desc")}</CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                    <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 p-4 bg-background/50 rounded-lg border">
                        <div>
                            <p className="text-sm font-medium text-muted-foreground">{t("billing_plan_label")}</p>
                            <h4 className="text-lg font-bold flex items-center gap-2">
                                {isGlobalPro ? (userPlan === 'monthly' ? 'Monthly Pro' : 'Yearly Pro') : (isTournamentPro ? 'Tournament Pro' : t("plan_free"))}
                                <Badge variant={isPro ? "secondary" : "outline"} className={`text-xs font-normal ${isPro ? "bg-green-100 text-green-700" : "border-primary/20 text-primary"}`}>
                                    {isPro ? 'Pro' : 'Free'}
                                </Badge>
                            </h4>
                        </div>
                        {!isPro && (
                            <Button
                                onClick={togglePayment}
                                disabled={showPayment}
                                className="w-full sm:w-auto"
                            >
                                {t("upgrade_button")}
                            </Button>
                        )}
                    </div>

                    {/* Inline Payment Section */}
                    {!isPro && showPayment && (
                        <div className="bg-background border rounded-lg p-6 animate-in fade-in slide-in-from-top-2">
                            <div className="flex justify-between items-start mb-4">
                                <div>
                                    <h4 className="font-semibold text-lg">{tBilling("pay_with_promptpay")}</h4>
                                    <p className="text-sm text-muted-foreground">{tBilling("scan_desc")}</p>
                                </div>
                                <Button variant="ghost" size="sm" onClick={() => setShowPayment(false)}>
                                    <X className="w-4 h-4" />
                                </Button>
                            </div>

                            {!paymentState.qrCode ? (
                                <div className="flex flex-col items-center justify-center p-8 space-y-4">
                                    <div className="text-center">
                                        {isGeneratingQR ? (
                                            <div className="flex flex-col items-center gap-2">
                                                <Loader2 className="w-8 h-8 animate-spin text-primary" />
                                                <p className="text-muted-foreground">{tCommon("loading")}</p>
                                            </div>
                                        ) : (
                                            <Button onClick={handleGenerateQR}>
                                                {tBilling("generate_qr")}
                                            </Button>
                                        )}
                                    </div>
                                </div>
                            ) : (
                                <div className="flex flex-col items-center space-y-6">
                                    {paymentState.status === 'success' ? (
                                        <div className="text-center space-y-2 py-8">
                                            <div className="w-16 h-16 bg-green-100 dark:bg-green-900 rounded-full flex items-center justify-center mx-auto">
                                                <Check className="w-8 h-8 text-green-600 dark:text-green-400" />
                                            </div>
                                            <h3 className="text-xl font-bold text-green-600 dark:text-green-400">{tBilling("payment_success")}</h3>
                                            <p className="text-muted-foreground">{tBilling("payment_success_desc")}</p>
                                        </div>
                                    ) : timeLeft <= 0 ? (
                                        <div className="flex flex-col items-center justify-center p-8 space-y-4 text-center">
                                            <div className="w-16 h-16 bg-muted rounded-full flex items-center justify-center">
                                                <Clock className="w-8 h-8 text-muted-foreground" />
                                            </div>
                                            <div>
                                                <h3 className="font-semibold text-lg">QR Code Expired</h3>
                                                <p className="text-sm text-muted-foreground">Please regenerate a new QR code to continue.</p>
                                            </div>
                                            <Button onClick={handleGenerateQR} disabled={isGeneratingQR}>
                                                {isGeneratingQR ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <RefreshCw className="w-4 h-4 mr-2" />}
                                                Regenerate QR
                                            </Button>
                                        </div>
                                    ) : (
                                        <>
                                            <div className="bg-white p-4 rounded-xl shadow-sm border border-border/50 relative">
                                                {/* eslint-disable-next-line @next/next/no-img-element */}
                                                <img
                                                    src={paymentState.qrCode}
                                                    alt="PromptPay QR Code"
                                                    className="w-64 h-64 object-contain mix-blend-multiply"
                                                />
                                                <div className="absolute -bottom-3 left-1/2 -translate-x-1/2 bg-background border shadow-sm px-3 py-1 rounded-full flex items-center gap-2 text-xs font-mono font-medium">
                                                    <Clock className="w-3 h-3 text-orange-500" />
                                                    <span className={timeLeft < 60 ? "text-red-500" : ""}>
                                                        {formatTime(timeLeft)}
                                                    </span>
                                                </div>
                                            </div>
                                            <div className="text-center">
                                                <p className="text-2xl font-bold text-primary">฿590.00</p>
                                                <p className="text-xs text-muted-foreground">PromptPay QR Payment</p>
                                            </div>
                                            <div className="flex flex-col items-center gap-2 w-full max-w-xs">
                                                <div className="flex items-center gap-2 text-primary font-medium animate-pulse text-sm">
                                                    <Loader2 className="w-3 h-3 animate-spin" />
                                                    <span>{tBilling("waiting_payment")}</span>
                                                </div>
                                                <p className="text-xs text-muted-foreground text-center animate-pulse">
                                                    Checking payment status automatically...
                                                </p>
                                            </div>
                                        </>
                                    )}
                                </div>
                            )}
                        </div>
                    )}

                    <div className="flex justify-end">
                        <Button variant="link" asChild className="px-0 text-muted-foreground hover:text-primary h-auto">
                            <Link href="/dashboard/billing">{t("view_pricing")}</Link>
                        </Button>
                    </div>
                </CardContent>
            </Card>

            <Card className="border-destructive/30">
                <CardHeader>
                    <CardTitle className="text-destructive">{t("danger_zone")}</CardTitle>
                    <CardDescription>{t("delete_desc")}</CardDescription>
                </CardHeader>
                <CardContent className="space-y-4">
                    {hasFixtures && (
                        <>
                            <div className="flex items-center justify-between">
                                <div>
                                    <h4 className="font-medium">{t("reset_fixtures")}</h4>
                                    <p className="text-sm text-muted-foreground">{t("reset_desc")}</p>
                                </div>
                                <Button variant="destructive" onClick={handleReset} disabled={isPending}>
                                    {isPending ? tCommon("loading") : t("reset_fixtures")}
                                </Button>
                            </div>
                            <Separator />
                        </>
                    )}
                    <div className="flex items-center justify-between">
                        <div>
                            <h4 className="font-medium">{t("delete_tournament")}</h4>
                            <p className="text-sm text-muted-foreground">{t("delete_desc")}</p>
                        </div>
                        <Button variant="destructive" onClick={handleDelete} disabled={isPending}>
                            {isPending ? tCommon("loading") : t("delete_tournament")}
                        </Button>
                    </div>
                </CardContent>
            </Card>
        </div >
    );
}
